<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MDMPI.App.Core\MDMPI.App.Core.csproj" />
    <ProjectReference Include="..\MDMPI.App.Data\MDMPI.App.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\Engineer\" />
    <Folder Include="Controllers\Collection\" />
    <Folder Include="Controllers\Ims\" />
    <Folder Include="Controllers\ProductSpecialist\" />
    <Folder Include="Controllers\Sales\" />
  </ItemGroup>

</Project>
