<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\Engineer\**" />
    <Compile Remove="Controllers\Ims\**" />
    <Compile Remove="Controllers\ProductSpecialist\**" />
    <Compile Remove="Controllers\Sales\**" />
    <Content Remove="Controllers\Engineer\**" />
    <Content Remove="Controllers\Ims\**" />
    <Content Remove="Controllers\ProductSpecialist\**" />
    <Content Remove="Controllers\Sales\**" />
    <EmbeddedResource Remove="Controllers\Engineer\**" />
    <EmbeddedResource Remove="Controllers\Ims\**" />
    <EmbeddedResource Remove="Controllers\ProductSpecialist\**" />
    <EmbeddedResource Remove="Controllers\Sales\**" />
    <None Remove="Controllers\Engineer\**" />
    <None Remove="Controllers\Ims\**" />
    <None Remove="Controllers\ProductSpecialist\**" />
    <None Remove="Controllers\Sales\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MDMPI.App.Core\MDMPI.App.Core.csproj" />
    <ProjectReference Include="..\MDMPI.App.Data\MDMPI.App.Data.csproj" />
  </ItemGroup>

</Project>
