-- Migration: add a_tblrequestpickupitemcategory (multi-category Pick Up)
-- Date: 2026-09-04
-- Run against the testing Postgres database before deploying the backend
-- build that returns/accepts ItemCategoryIDs on RequestPickUp.
--
-- A Pick Up request may carry several item categories. The scalar
-- itemcategoryid column on a_tblrequestpickupmdmpi keeps the FIRST
-- (primary) selection for backward compatibility; this child table holds
-- the full selection, mirroring a_tblrequestdocumentreference.

CREATE TABLE IF NOT EXISTS public.a_tblrequestpickupitemcategory (
    pickupitemcategoryid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requestid bigint NOT NULL,
    itemcategoryid bigint NOT NULL,
    CONSTRAINT uq_a_tblrequestpickupitemcategory UNIQUE (requestid, itemcategoryid),
    CONSTRAINT fk_a_tblrequestpickupitemcategory_request FOREIGN KEY (requestid)
        REFERENCES public.a_tblrequestpickupmdmpi (requestid)
        ON DELETE CASCADE
);

ALTER TABLE public.a_tblrequestpickupitemcategory OWNER TO postgres;

CREATE INDEX IF NOT EXISTS idx_a_tblrequestpickupitemcategory_requestid
    ON public.a_tblrequestpickupitemcategory (requestid);

-- Backfill: existing single-category requests get one child row each.
INSERT INTO public.a_tblrequestpickupitemcategory (requestid, itemcategoryid)
SELECT requestid, itemcategoryid
FROM public.a_tblrequestpickupmdmpi
WHERE itemcategoryid IS NOT NULL
ON CONFLICT (requestid, itemcategoryid) DO NOTHING;
