-- Migration: add a_tblloseitem (lost items on Pull Out / Return requests)
-- Date: 2026-09-03
-- Run against the testing Postgres database before deploying the backend
-- build that includes LoseItemController.
--
-- An item's absence from this table means it was included in the pull out;
-- a row means the item was lost / not pulled out, with the courier's remarks.

CREATE TABLE IF NOT EXISTS public.a_tblloseitem (
    loseitemid bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requestid bigint NOT NULL,
    itemcode character varying(100),
    remarks character varying(500),
    createdat timestamp without time zone,
    CONSTRAINT fk_a_tblloseitem_request FOREIGN KEY (requestid)
        REFERENCES public.a_tblrequestpulloutreturnpickup (requestid)
        ON DELETE CASCADE
);

ALTER TABLE public.a_tblloseitem OWNER TO postgres;

CREATE INDEX IF NOT EXISTS idx_a_tblloseitem_requestid
    ON public.a_tblloseitem (requestid);
