<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Engineer\**" />
    <Compile Remove="Ims\**" />
    <Compile Remove="ProductSpecialist\**" />
    <Compile Remove="Sales\**" />
    <EmbeddedResource Remove="Engineer\**" />
    <EmbeddedResource Remove="Ims\**" />
    <EmbeddedResource Remove="ProductSpecialist\**" />
    <EmbeddedResource Remove="Sales\**" />
    <None Remove="Engineer\**" />
    <None Remove="Ims\**" />
    <None Remove="ProductSpecialist\**" />
    <None Remove="Sales\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MDMPI.App.Core\MDMPI.App.Core.csproj" />
    <ProjectReference Include="..\MDMPI.App.Common\MDMPI.App.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Collection\Migrations\" />
    <Folder Include="Database\" />
    <Folder Include="Logistic\Migrations\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.9" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
