<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MDMPI.App.Core\MDMPI.App.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Collection\" />
    <Folder Include="Engineer\Migrations\" />
    <Folder Include="Engineer\Repositories\" />
    <Folder Include="Ims\Migrations\" />
    <Folder Include="Ims\Repositories\" />
    <Folder Include="Collection\Migrations\" />
    <Folder Include="Logistic\Migrations\" />
    <Folder Include="Logistic\Repositories\" />
    <Folder Include="Collection\Repositories\" />
    <Folder Include="ProductSpecialist\Migrations\" />
    <Folder Include="ProductSpecialist\Repositories\" />
    <Folder Include="Sales\Migrations\" />
    <Folder Include="Sales\Repositories\" />
  </ItemGroup>

</Project>
